[package]
name = "rich-swap"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.9"
ic-cdk = "0.11"
ic-cdk-macros = "0.8"
ic-cdk-timers = "0.5"
ic-stable-memory = "0.4"
ic-stable-memory-derive = "0.4"
ic-ledger-types = "0.8"
icrc-ledger-types = "0.1.4"
serde = { version = "1.0", features = ["derive"] }
syn = "1.0"
anyhow =  "1"
thiserror = "1"
generic-array = "0.14"
cfg-if = "1.0"
hex = "0.4"
rust_decimal = { version = "1.28", features = ["serde-str", "maths"] }
rust_decimal_macros = "1.28"
lazy_static = "1.5"

bitcoin = { version = "0.30.1", default-features = false, features = ["no-std"] }
